spring.application.name=backend

#database connection with postgre (NOT STARTED YET)

spring.datasource.url=jdbc:postgresql://localhost:5432/XXXXXXX
spring.datasource.username=
spring.datasource.password=

# for auto update the tables hibernate 

spring.jpa.hibernate.ddl-auto= update

# for see sql on console for knowing whats jpa Doing

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


